#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd ) #"

# Load O2PHYSICS
source ${SCRIPT_DIR}/enable
env | sort > ${SCRIPT_DIR}/compilation_env.txt

export CMAKE_DEBUG_OPTS=""

ARGS=()
while [[ $# -gt 0 ]]; do
  case $1 in
    debug)
      export CMAKE_DEBUG_OPTS=" --debug-output --debug-find --trace --trace-expand --trace-format=human --trace-redirect=cmake_trace.log "
      shift
      ;;
    -h|--help)
      echo -e "debug\t: enable cmake debug options"
      exit 0
      ;;
    *)
      ARGS+=("${1}") # save positional arg
      shift # past argument
      ;;
  esac
done

set -- "${ARGS[@]}" # restore positional parameters

pushd ${SCRIPT_DIR} &> /dev/null

# Compile the tasks
mkdir -p BUILD
rm -rf BUILD/*

pushd BUILD &> /dev/null || { echo "Could not cd to BUILD dir"; exit 1; }

cmake -DCMAKE_INSTALL_PREFIX=.. -DBUILD_TEST_ROOT_MACROS=OFF ${CMAKE_DEBUG_OPTS} \
    -DENABLE_CUDA=OFF -DENABLE_OPENCL1=OFF -DENABLE_OPENCL2=OFF -DENABLE_HIP=OFF \
    -DLIBJALIENO2_INCLUDE_DIR=${LIBJALIENO2_ROOT}/include -DLIBJALIENO2_LIBPATH=${LIBJALIENO2_ROOT}/lib/libjalienO2.so \
    -DJALIEN_ROOT_INCLUDE_DIR=${JALIEN_ROOT_ROOT}/include -DJAliEnRoot_LIB=${JALIEN_ROOT_ROOT}/lib/libJAliEnROOT.so \
    .. 2>&1 | tee cmake_out.log
RET=$?

[[ "${RET}" == 0 ]] && { make -j4 2>&1 | tee compile.log; } || { popd  &> /dev/null; echo "cmake failure"; exit ${RET}; }

rm -rf ../bin/*  ## we are in BUILD
[[ "${RET}" == 0 ]] && { make install 2>&1 | tee install.log; } || { popd &> /dev/null;  echo "make failure"; exit ${RET}; }

popd &> /dev/null  # return to SCRIPT_DIR

popd &> /dev/null  # return to original location

